require("engine/test/bustedhelper")
local easing = require("engine/core/easing")

describe('linear', function ()
  it('should return the same value as input', function ()
    assert.are_equal(0, easing.linear(0))
    assert.are_equal(0.5, easing.linear(0.5))
    assert.are_equal(1, easing.linear(1))
    assert.are_equal(0.73, easing.linear(0.73))
  end)
end)

describe('ease_in', function ()
  it('should return 0 when t=0', function ()
    assert.are_equal(0, easing.ease_in(0))
    assert.are_equal(0, easing.ease_in(0, 3))
  end)
  it('should return 1 when t=1', function ()
    assert.are_equal(1, easing.ease_in(1))
    assert.are_equal(1, easing.ease_in(1, 3))
  end)
end)

describe('ease_out', function ()
  it('should return 0 when t=0', function ()
    assert.are_equal(0, easing.ease_out(0))
    assert.are_equal(0, easing.ease_out(0, 3))
  end)
  it('should return 1 when t=1', function ()
    assert.are_equal(1, easing.ease_out(1))
    assert.are_equal(1, easing.ease_out(1, 3))
  end)
end)

describe('ease_in_out', function ()
  it('should return a value between 0 and 1 at t=0.5', function ()
    local val = easing.ease_in_out(0.5)
    assert.is_true(val > 0 and val < 1)
  end)
  it('should be symmetric around t=0.5', function ()
    -- ease_in_out(0.5 - delta) + ease_in_out(0.5 + delta) should equal 1
    local delta = 0.2
    local val_low = easing.ease_in_out(0.5 - delta)
    local val_high = easing.ease_in_out(0.5 + delta)
    assert.are_equal(1, val_low + val_high)
  end)
end)

describe('ease_out_bounce', function ()
  it('should return 1 when t=1', function ()
    assert.are_equal(1, easing.ease_out_bounce(1))
  end)
end)
