require("engine/test/bustedhelper")
require("engine/core/vector_ext_rotate_90")

describe('rotated_90_cw', function ()
  it('(1 -3).rotated_90_cw() => (3, 1)', function ()
    assert.are_same(vector(3, 1), vector(1, -3):rotated_90_cw())
  end)
end)

describe('rotate_90_cw_inplace', function ()
  it('(1 -3).rotate_90_cw_inplace() => (3, 1)', function ()
    local v = vector(1, -3)
    v:rotate_90_cw_inplace()
    assert.are_same(vector(3, 1), v)
  end)
end)

describe('rotated_90_ccw', function ()
  it('(1 -3).rotated_90_ccw() => (-3, -1)', function ()
    assert.are_same(vector(-3, -1), vector(1, -3):rotated_90_ccw())
  end)
end)

describe('rotate_90_ccw_inplace', function ()
  it('(1 -3).rotate_90_ccw_inplace() => (-3, -1)', function ()
    local v = vector(1, -3)
    v:rotate_90_ccw_inplace()
    assert.are_same(vector(-3, -1), v)
  end)
end)
